name: Main

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: ./gradlew build -i
      - name: Cache .gradle
        uses: actions/cache@v1
        with:
          path: .gradle
          key: ${{ runner.os }}-dotgradle-${{ hashFiles('**/build.gradle') }}
          restore-keys: |
            ${{ runner.os }}-dotgradle-
      - name: Cache gradle
        uses: actions/cache@v1
        with:
          path: /home/runner/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
